import Header from "@/components/header";
import "./global.css";
import "./style.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
  modal
}: {
  children: React.ReactNode,
  modal: React.ReactNode,
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>
          {modal}
          {children}
        </main>
      </body>
    </html>
  )
}
